name: Android CI

on: [push]

jobs:
#  build:
#    name: Run Build
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Build
#        run: ./gradlew build
#
#  test:
#    name: Run Unit Tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Unit Tests
#        run: ./gradlew test
#
#  androidTest:
#    name: Run Android Instrumentation Tests
#    runs-on: macOS-10.15
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: set up JDK 1.8
#        uses: actions/setup-java@v1
#        with:
#          java-version: 1.8
#      - name: Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 21
#          script: ./gradlew connectedAndroidTest

  codeCoverage:
    name: Run Code Coverage Tests
    runs-on: macOS-10.15

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Code Coverage Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          script: ./gradlew jacocoTestCoverageVerification

      - name: Publish Code Coverage To Code Climate
        uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 0762e2e0f516de5ebe1df0f0c628dcf26ea02008e766aed8ba7d1001aa442410
        with:
          coverageCommand: ./gradlew jacocoTestCoverageVerification
          debug: true


